//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Stats {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.Stats.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumed fooditems.
        /// </summary>
        public static string ConsumedFooditems {
            get {
                return ResourceManager.GetString("ConsumedFooditems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumed today.
        /// </summary>
        public static string ConsumedToday {
            get {
                return ResourceManager.GetString("ConsumedToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily nutrient intake.
        /// </summary>
        public static string DailyNutrientIntake {
            get {
                return ResourceManager.GetString("DailyNutrientIntake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fooditem.
        /// </summary>
        public static string Fooditem {
            get {
                return ResourceManager.GetString("Fooditem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutrient.
        /// </summary>
        public static string Nutrient {
            get {
                return ResourceManager.GetString("Nutrient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Intake level.
        /// </summary>
        public static string RecommendedIntakeLevel {
            get {
                return ResourceManager.GetString("RecommendedIntakeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerable Upper intake level.
        /// </summary>
        public static string TolerableUpperintakeLevel {
            get {
                return ResourceManager.GetString("TolerableUpperintakeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your personal nutrition statistics.
        /// </summary>
        public static string YourPersonalNutritionStatistics {
            get {
                return ResourceManager.GetString("YourPersonalNutritionStatistics", resourceCulture);
            }
        }
    }
}
